### ISSUE TITLE
Infinite Zoom

### ISSUE THREAD

**Issue by lunatico67** [Isi-dev/ComfyUI-Animation_Nodes_and_Workflows#1]
Is it possible to infinite zoom with the Move In_Or_Out node?  Create a perfect loop, in the gif of the example it gives an abrupt jump.

**Comment by Isi-dev** [comment]
> Is it possible to infinite zoom with the Move In_Or_Out node? Create a perfect loop, in the gif of the example it gives an abrupt jump.

The Move In_Or_Out node zooms in or out of the background image while keeping the foreground stationary, so it is limited by the size and scaling of the background image. I created the gif from an mp4 file with very short duration for demonstration because the MB size of the gif is too high. I guess a perfect loop can be created if there's a way to sync the beginning and end of the gif.

**Comment by lunatico67** [comment]
Thanks for the information and the quick help
